version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: db_simple_banking
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
  api:
    depends_on:
      - mysql
    container_name: api
    build: .
    ports:
      - 8080:8080